### ISSUE TITLE
Tooltip/Popover arrow sizing

### ISSUE THREAD

**Issue by thefrontendwizard** [reakit/reakit#383]
## 🚀 Feature request

There needs to be a better way to do custom arrow sizes other than changing the `font-size` and forcing it with `!important`.

### Example

Currently to change the size of the arrow you have to do something like this:
```css
.arrow {
  font-size: 16px !important;
}
```

### Possible implementations

Perhaps a prop on the arrow component like `size`?
