### ISSUE TITLE
Getting weird clipping on Backdrop when used with Docz

### ISSUE THREAD

**Issue by stramel** [reakit/reakit#404]
### Current behavior

The `DialogBackdrop` appears to be having some strange issues with its position in the DOM.

![image](https://user-images.githubusercontent.com/855184/61761666-00671a00-ad95-11e9-9b31-3a59ca8e1acd.png)

Any `Playground` after the modal that you trigger appears above/"to clip" the `DialogBackdrop`.

The `Playground` has these styles applied by Docz.

```css
    top: 0;
    left: 0;
    z-index: 0;
    position: relative;
    width: auto;
    height: auto;
    padding: 0px;
    margin: 0 0 30px;
    background: transparent;
    box-sizing: border-box;
    -webkit-transition: background 0.3s;
    transition: background 0.3s;
```

The `DialogBackdrop` has these styles applied by me:

```css
  background-color: rgba(0, 0, 0, 0.5);
  position: fixed;
  top: 0;
  right: 0;
  bottom: 0;
  left: 0;
  z-index: 9998;
  transition: opacity 300ms;
  opacity: 1;

  &.hidden {
    opacity: 0;
  }
```

### Expected behavior

I expect the `DialogBackdrop` to be over all other elements in this page.
